export default {
  DB_NOOP: 'DB_NOOP',
  DB_QUERYING: 'DB_FINDING',
  DB_IS_FINDING: 'DB_IS_FINDING',
  DB_QUERYING_OFF: 'DB_FINDING_OFF',
  DB_IS_CREATING: 'DB_IS_CREATING',
  DB_IS_UPDATING: 'DB_IS_UPDATING',
  DB_IS_REMOVING: 'DB_IS_REMOVING',
  DB_FIND_RESULT: 'DB_FIND_RESULT',
  DB_SAVED: 'DB_SAVED',
  DB_UPDATED: 'DB_UPDATED',
  DB_REMOVE_RESULT: 'DB_REMOVE_RESULT'
}
