export default {
  // ERRORS
  FEEDBACK_DISPLAY_ERROR: 'FEEDBACK_DISPLAY_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  // MESSAGES
  FEEDBACK_DISPLAY_ERROR: 'FEEDBACK_DISPLAY_MESSAGE',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE'

};
